### ISSUE TITLE
GPL license for libraries

### ISSUE THREAD

**Issue by hbbio** [githwxi/ATS-Postiats#154]
ATS looks very interesting.
However, using the GPL license for the standard library restricts its usage to writing GPLv3 programs.

- Do you confirm this?
- Would a change to a more permissive license (for libraries only) be considered?

**Comment by master-q** [comment]
This page is good for you?

https://github.com/githwxi/ATS-Postiats/wiki/Frequently-asked-questions#ats-library-code-is-gplv3-so-does-this-mean-my-compiled-code-also-must-be-gplv3

**Comment by hbbio** [comment]
Thanks. It should be noted in the main README which has contradictory terms.

**Comment by master-q** [comment]
> Thanks. It should be noted in the main README which has contradictory terms.

Ah... You are right... But it's Hongwei's issue...

**Comment by githwxi** [comment]
Okay, I have just reworded the part on Licenses for ATS2 in README.md.

The license for the source of the libraries(prelude, libc, libats) is GPLv3

The license for the object code of the libraries(prelude, libc, libats) is LGPL2.1

The header files for the libraries are released separately under a BSD license.

**Comment by githwxi** [comment]
I reworded the part on licenses in the README file:

######

Licenses for ATS2

The Compiler (ATS/Postiats): GPLv3
The source for Libraries (ATSLIB/{prelude,libc,libats}): GPLv3
The object code for Libraries (ATSLIB/{prelude,libc,libats}): LGPLv2.1
There is a separate release under the BSD license for the C header files of
the Libraries, which one can freely insert into the C code
generated from ATS source code.

######

**Comment by master-q** [comment]
Thanks. :)

**Comment by hbbio** [comment]
Thanks Hongwei!

**Comment by githwxi** [comment]
Le mercredi 27 janvier 2016 15:30:59 UTC+1, gmhwxi a écrit :
>
> The object code for Libraries (ATSLIB/{prelude,libc,libats}): LGPLv2.1
>

So statically linking to the standard ATS library is not possible?

**Comment by githwxi** [comment]
What do you mean? LGPL let's you link to LGPLed software however you want, 
but you can't change the LGPLed software licence and should provide source 
for the LGPL software (*It applies to LGPL software only*). Other parts, 
for example your code, could be covered with any licence you want. You also 
can release your software under LGPL or compatible licence. So what's the 
problem?

**Comment by githwxi** [comment]
Le jeudi 11 février 2016 10:37:30 UTC+1, anonymous anonymous a écrit :
>
> What do you mean? LGPL let's you link to LGPLed software however you want, 
>

LGPL is contaminating through static linking. To allow static linking, it 
needs a special exception which must be explicitly stated.

**Comment by githwxi** [comment]
Given that we are talking about licenses here, I want to reiterate
that ATS can be considered a no-runtime and no-library language.

The no-runtime part is easy to understand. ATS is a no-library language
in the sense that one can easily write ATS programs that do not need to
be linked to any ATS library code. I often have a mylib.dats file in a 
project.
For instance,

https://github.com/githwxi/ATS-Postiats-contrib/blob/master/projects/SMALL/Calculator/calculator_mylib.dats

The following lines are taken from calculator_mylib.dats:

local
//
#include
"prelude/DATS/filebas.dats"
//
in (* in of [local] *)
//
// HX: it is intentionally left to be empty
//
end // end of [local]

These lines allow the compiler to generate the code for some needed ATS 
library functions.
We can afford this style because the vast majority of ATS library functions 
are templates, which
do not get to be compiled into object code directly.

**Comment by githwxi** [comment]
I greatly apologize for my first naive reply. I didn't know that LGPL has 
such requirement. I will not misinform people on this subject anymore. Even 
though I can see why FSF made it that way, the exception is often needed 
indeed.

Best regards,
anonymous
